name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image and Push
        run: |
          version=$(grep -oP '"version":\s*"\K[0-9]+\.[0-9]+\.[0-9]+' package.json)
          docker build -t heavygee/hello-dalle-discordbot:latest .
          docker tag heavygee/hello-dalle-discordbot:latest heavygee/hello-dalle-discordbot:$version
          docker push heavygee/hello-dalle-discordbot:latest
          docker push heavygee/hello-dalle-discordbot:$version
